### ISSUE TITLE
resend confirmation email

### ISSUE THREAD

**Issue by jpiepkow** [AppDoctorIo/accesspass#22]
Add a route to resend the confirmation email potentially.

**Comment by anandtrex** [comment]
This would be a really useful feature to have.

**Comment by jpiepkow** [comment]
I can not add this feature atm but am always open to PRs. I can provide guidance in this thread.

**Comment by anandtrex** [comment]
I've started a PR here: #46

**Comment by jpiepkow** [comment]
@anandtrex , that pr looks good. Are you ready for me to merge and publish it to hex?

**Comment by anandtrex** [comment]
Let me just bump up the version number. Should I make it 1.0.4 or 1.1.0? The latter seems to be more meaningful since it adds a new endpoint.

**Comment by jpiepkow** [comment]
1.1.0 for a new feature that is not breaking. Thanks for taking the time on this!

**Comment by anandtrex** [comment]
Should be ready to go now. Thank you!

**Comment by jpiepkow** [comment]
@anandtrex that has been published to hex. If you could make sure its all working correctly again as I had to make a small change to get the publish working(its been a while). Thanks again for your help on the PR!

**Comment by anandtrex** [comment]
@jpiepkow Just tested some of it out and it works great. I realised that I didn't update the documentation for the new API call. I'll do that and send you a PR.

**Comment by jpiepkow** [comment]
Thanks again, I appreciate it.
