### ISSUE TITLE
Support for invites

### ISSUE THREAD

**Issue by anandtrex** [AppDoctorIo/accesspass#38]
Would you consider adding support for invitations during registration?

At the simplest, it seems like it would involve three things:
1. A form for signing up for an invitation. This could be the same as the current registration form, except that it doesn't create an account that can be used for logging in yet (it's not "active").
2. A commandline mix task for send out invites to specific people or "earliest x registrants" etc.
3. An invite link that "activates" the account.

**Comment by jpiepkow** [comment]
Thanks for the issue. I do believe this is slightly outside of the scope of what accesspass is trying to accomplish. I will say though you should be able to add an endpoint to the api that accesspass is being used and handle the invitation creation logic. I do this with my application for beta codes as its currently in closed beta: https://app.appdoctor.io/register The hooks accesspass provides should be enough to validate a new registration based on a code or whatever logic you add to your actual api.

If you have any other questions on how you could do this feel free to comment back on this ticket after it is closed and we can discuss further!
