### ISSUE TITLE
Incompatible with Ecto 3.x.x

### ISSUE THREAD

**Issue by dfalling** [AppDoctorIo/accesspass#43]
I've opened a PR that addresses this (and fixes a few code style warnings as well:
#41

**Comment by jpiepkow** [comment]
Is this a breaking pr or will older versions of ecto still work?

**Comment by dfalling** [comment]
Good call- I checked ecto 2.0.4 (the min for accesspass) and its changeset.cast can take atoms or binaries, so we should be backwards compatible.

https://hexdocs.pm/ecto/2.0.2/Ecto.Changeset.html#cast/3

**Comment by jpiepkow** [comment]
Alright, I will merge the pr and get it pushed up on hex this weekend. Thanks again!
