### ISSUE TITLE
Confirmation link in email doesn't match route provided by accesspass

### ISSUE THREAD

**Issue by anandtrex** [AppDoctorIo/accesspass#45]
AccessPass provides a *POST* route for `/confirm`, but the confirmation email contains an URL with a GET request.

**Comment by jpiepkow** [comment]
@anandtrex You can override the email sent but the idea behind it currently is that it will redirect a user to UI(that you have created independent of accesspass) and that page will fire the post request/handle the response from accesspass.

**Comment by anandtrex** [comment]
Gothcha. That makes sense, thanks (also for the quick response)!
